services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: qtim-redis
    environment:
      # REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      # REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    ports:
      - '6380:6379'
    volumes:
      - ./redisdata:/data
  
volumes:
  pgdata:
  redisdata:
